SELECT  Q.*,  R.F_NAME AS F_DEALINGSNAME, P.F_CONTRACTNO, P.F_WORKNO, P.F_REMARK,
              Q.F_APAMT-Q.F_PAMT AS F_AMT  
FROM
(
SELECT B.F_ARPID AS F_BILLID, B.F_DEALINGSID, LEFT(B.F_DATE, 10) AS F_DATE, A.F_PURBILLID,  
           SUM(IFNULL(A.F_AMT, 0)) AS F_APAMT, 0 AS F_PAMT, B.F_WORKNO, B.F_REMARK   
FROM ACC_ARPBILLBODY A
LEFT JOIN ACC_ARPBILLHEAD B ON(A.F_ARPID=B.F_ARPID)
WHERE B.F_DEALINGSID=:F_SUPPLIERID AND B.F_STATUS>='5'
GROUP BY  B.F_ARPID, B.F_DEALINGSID, B.F_DATE, A.F_PURBILLID

UNION ALL

SELECT B.F_RPID AS F_BILLID, B.F_DEALINGSID, LEFT(B.F_DATE, 10) AS F_DATE, A.F_PURBILLID, 
       0 AS F_APAMT, SUM(IFNULL(F_ACTAMT, 0)) AS F_PAMT, B.F_WORKNO, B.F_REMARK   
FROM ACC_RPBILLBODY A
LEFT JOIN ACC_RPBILLHEAD B ON(A.F_RPID=B.F_RPID)
WHERE B.F_DEALINGSID=:F_SUPPLIERID AND B.F_STATUS>='5'
GROUP BY B.F_RPID, B.F_DEALINGSID, B.F_DATE, A.F_PURBILLID

) Q
LEFT JOIN DB_ORGS R ON(Q.F_DEALINGSID=R.F_ID)
LEFT JOIN PUR_ORDERHEAD P ON(Q.F_PURBILLID=P.F_BILLID)
ORDER BY F_PURBILLID, F_DATE, F_BILLID