SELECT  F_DEPTNAME  AS 部门名称 , F_CURRENCY AS 币别,cast( SUM(PREAMT30+PREAMT60+PREAMT90+PREAMT180)  as decimal(11,3))  AS 预付总金额 , 
cast(SUM(PREAMT30)  as decimal(11,3))  AS 预付1个月内,
cast(SUM(PREAMT60)  as decimal(11,3))  AS 预付超1个月,
cast(SUM(PREAMT90)  as decimal(11,3))  AS 预付超2个月, 
CAST(SUM(PREAMT180) as decimal(11,3)) AS 预付超3个月

FROM
/* L6、计算各个时间区间的预付金额 */
(
SELECT D.F_NAME AS F_DEPTNAME,C.F_SNAME,F_PURBILLID,F_CONTRACTNO,L6.F_CURRENCY,PREAMT AS 总金额,PREAMT30,PREAMT60,PREAMT90,PREAMT180
 FROM
    (
        SELECT L4.F_PURBILLID,F_DEPTNAME,F_SUPPLIERID,F_CONTRACTNO,L4.F_CURRENCY,
                ROUND(ACTAMT-RECAMT,6) AS PREAMT,
                IF(AM30-IF(AM180+AM90+AM60-RECAMT>0,0,RECAMT-AM180-AM90-AM60)>0 , AM30-IF(AM180+AM90+AM60-RECAMT>0,0,RECAMT-AM180-AM90-AM60),0) AS PREAMT30, 
                IF(AM60-IF(AM180+AM90-RECAMT>0,0,RECAMT-AM180-AM90)>0 , AM60-IF(AM180+AM90-RECAMT>0,0,RECAMT-AM180-AM90),0) AS PREAMT60  , 
                IF(AM90-IF(AM180-RECAMT>0,0,RECAMT-AM180)>0 , AM90-IF(AM180-RECAMT>0,0,RECAMT-AM180),0) AS PREAMT90 ,
                IF(AM180-RECAMT>0,AM180-RECAMT,0) AS   PREAMT180,
                L5.F_APPROVETIME
        FROM
            /* L4、把金额 按采购订单汇总  */
            (
            SELECT F_PURBILLID,F_CURRENCY,SUM(F_ACTAMT) AS ACTAMT,SUM(AMT30) AS AM30 , SUM(AMT60) AS AM60 ,SUM(AMT90) AS  AM90 , SUM(AMT180)  AS AM180
            FROM 
                /* L3、把金额分为0-30天，30-60天，60-90天，90天以上的区间 */
                (
                    SELECT F_RPID,F_PURBILLID,F_CURRENCY,
                        F_ACTAMT,
                        IF(F_CHECKDATE<30,F_ACTAMT,0) AS AMT30,
                        IF(F_CHECKDATE>=30 AND F_CHECKDATE<60,F_ACTAMT,0) AS AMT60,
                        IF(F_CHECKDATE>=60 AND F_CHECKDATE<90,F_ACTAMT,0) AS AMT90,
                        IF(F_CHECKDATE>=90,F_ACTAMT,0) AS AMT180
                    FROM 
                    /* L1、取付款单的单号，把审核日期转成数字形式，采购订单号，金额大于0，币别，并汇总 */
                    (
                        select  A.F_RPID,TO_DAYS(NOW())-TO_DAYS(B.F_CHECKDATE) AS F_CHECKDATE,A.F_PURBILLID , SUM(IFNULL(A.F_ACTAMT, 0)) AS F_ACTAMT,B.F_CURRENCY
                        FROM ACC_RPBILLBODY A
                        LEFT JOIN  ACC_RPBILLHEAD B ON B.F_RPID=A.F_RPID
                        WHERE B.F_STATUS>=5  AND B.F_RPTYPE=2 AND B.F_PAYTYPE=1 AND  A.F_ACTAMT>0
                        GROUP BY  A.F_RPID,B.F_CHECKDATE,IFNULL( A.F_PURBILLID,B.F_PURBILLID),B.F_CURRENCY
                    ) L1
                ) L3
                GROUP BY F_PURBILLID,F_CURRENCY
            ) L4
        LEFT JOIN 
            /*  L5、 每张采购订单的 已入库金额 */
            (
                SELECT F_BILLID,F_DEPTNAME,F_SUPPLIERID,F_CONTRACTNO,F_CURRENCY,RECAMT1-IFNULL(F_ACTAMT,0) AS RECAMT,F_APPROVETIME
                FROM 
                (
                SELECT A.F_BILLID,F_DEPTNAME,B.F_SUPPLIERID,B.F_CONTRACTNO,F_CURRENCY,IFNULL(SUM(F_RECVQTY*F_PRICE),0) AS RECAMT1,B.F_APPROVETIME
                                FROM PUR_ORDERBODY A
                                LEFT JOIN PUR_ORDERHEAD B ON A.F_BILLID=B.F_BILLID
                                WHERE B.F_STATUS>=5 
                                GROUP BY A.F_BILLID,F_DEPTNAME,B.F_SUPPLIERID,B.F_CONTRACTNO,F_CURRENCY
                ) A
                LEFT JOIN 
                (
                SELECT F_PURBILLID, SUM(F_ACTAMT) AS F_ACTAMT 
                    FROM ACC_RPBILLBODY 
                    WHERE F_ACTAMT<0
                GROUP BY F_PURBILLID
                ) B
                ON B.F_PURBILLID=A.F_BILLID
            ) L5
        ON  L4.F_PURBILLID=L5.F_BILLID
    ) L6
LEFT JOIN  DB_ORGS C ON F_SUPPLIERID=C.F_ID
LEFT JOIN  DB_ORGS D ON C.F_PID=D.F_ID
WHERE PREAMT>1
AND L6.F_APPROVETIME>=:START_DATE AND L6.F_APPROVETIME<=DATE_ADD(:END_DATE,interval 1 day)
AND (:采购部门='' OR F_DEPTNAME LIKE CONCAT('%',:采购部门,'%'))
AND (:供应商='' OR F_SUPPLIERID LIKE CONCAT('%',:供应商,'%'))
ORDER BY F_DEPTNAME,F_CURRENCY,总金额 DESC
) L6
WHERE PREAMT30+PREAMT60+PREAMT90+PREAMT180>0
GROUP BY F_DEPTNAME,F_CURRENCY

/*----------------------------------------------------------------------------*/

SELECT  B.F_BOXIDX AS 柜序号,
        A.F_BOXMODEL AS 柜型,
        A.F_WORKNO AS 工作号,
        C.F_GOODSCODE  AS 物品代码,
        C.F_GOODSNAME AS 物品名称,
        C.F_GOODSMODEL AS 型号规格,
        C.F_GOODSPACKAGEMODEL AS 包装规格,
        B.F_ACTQTY/B.F_EXRATE AS 数量,
        D.F_REFUNIT AS 常用单位,
        B.F_TOTALWEIGHT/B.F_WEIGHTRATE AS 总重量,
        CAST(D.F_PRICE*D.F_EXRATE  AS   DECIMAL(10,4)) AS 采购单价,
        CAST(D.F_ACTPRICE*D.F_EXRATE  AS   DECIMAL(10,4)) AS 单价,
        D.F_ACT01 AS 采购成本,
        D.F_AMTRETURN AS 退税额,
        D.F_ACT02 AS 转运费,
        D.F_ACT04 AS 单证费用,
        D.F_ACTFOB AS FOB价,
        D.F_ACTFOBADD AS 加点FOB,
        D.F_ACT05 AS 海运费,
        D.F_ACTCIF AS CIF价,
        D.F_ACT11 AS 清关费,
        D.F_ACT12 AS 拖车费,
        D.F_ACT13 AS 仓库费,
        D.F_CST14 AS 税费,
        D.F_ACT03 AS 其他采购费,
        D.F_ACT15 AS 其他费,
        D.F_ACTAMT AS 实际成本,
         CONCAT(K.F_COLORNO,'') AS  批次,
        E.TKT AS 实际入库时间

   FROM MPS_SOBOXNO A
   LEFT JOIN MPS_SOBODY B ON (B.F_WORKNO=A.F_WORKNO AND B.F_BOXIDX=A.F_BOXIDX)
   LEFT JOIN BAS_GOODS C ON C.F_GOODSID=B.F_GOODSID
   LEFT JOIN CST_TOTAL D ON D.F_SOURCEID=B.F_ID
   LEFT JOIN MPS_SOBODY_SPALLET K  ON   K.F_BILLITEMID=B.F_ID
   LEFT JOIN (SELECT MIN(F_RECEDATE) AS TKT, F_WORKNO FROM MPS_SOBOXNO GROUP BY F_WORKNO) E ON E.F_WORKNO = A.F_WORKNO 
   WHERE B.F_ACTQTY>0  
        AND E.TKT>=:START_DATE AND E.TKT<=DATE_ADD(:END_DATE,interval 1 day)
        AND (:工作号='' OR B.F_WORKNO LIKE CONCAT('%',:工作号,'%'))
        AND (:物品代码='' OR C.F_GOODSCODE LIKE CONCAT('%',:物品代码,'%'))
        AND (B.F_CI=%F_CI OR B.F_ORGID=%F_CI)
       
        ORDER BY B.F_BOXIDX,B.F_ISMAIN DESC,C.F_GOODSTYPENAME,C.F_GOODSTYPECODE,C.F_GOODSNAME,C.F_GOODSCODE

/*----------------------------------------------------------------------------*/

SELECT  Q.*,  R.F_NAME AS F_DEALINGSNAME, P.F_CONTRACTNO, Q.F_WORKNO, P.F_REMARK,
              Q.F_APAMT-Q.F_PAMT AS F_AMT  
FROM
(
SELECT B.F_ARPID AS F_BILLID, B.F_DEALINGSID, LEFT(B.F_DATE, 10) AS F_DATE, A.F_PURBILLID,  
           SUM(IFNULL(A.F_AMT, 0)) AS F_APAMT, 0 AS F_PAMT, B.F_WORKNO, B.F_REMARK   
FROM ACC_ARPBILLBODY A
LEFT JOIN ACC_ARPBILLHEAD B ON(A.F_ARPID=B.F_ARPID)
WHERE B.F_DEALINGSID=:F_SUPPLIERID AND B.F_STATUS>='5'
GROUP BY  B.F_ARPID, B.F_DEALINGSID, B.F_DATE, A.F_PURBILLID,B.F_WORKNO, B.F_REMARK

UNION ALL

SELECT B.F_RPID AS F_BILLID, B.F_DEALINGSID, LEFT(B.F_DATE, 10) AS F_DATE, A.F_PURBILLID, 
       0 AS F_APAMT, SUM(IFNULL(F_ACTAMT, 0)) AS F_PAMT, B.F_WORKNO, B.F_REMARK   
FROM ACC_RPBILLBODY A
LEFT JOIN ACC_RPBILLHEAD B ON(A.F_RPID=B.F_RPID)
WHERE B.F_DEALINGSID=:F_SUPPLIERID AND B.F_STATUS>='5'
GROUP BY B.F_RPID, B.F_DEALINGSID, B.F_DATE, A.F_PURBILLID,B.F_WORKNO, B.F_REMARK   

) Q
LEFT JOIN DB_ORGS R ON(Q.F_DEALINGSID=R.F_ID)
LEFT JOIN PUR_ORDERHEAD P ON(Q.F_PURBILLID=P.F_BILLID)
ORDER BY F_PURBILLID, F_DATE, F_BILLID

/*-----------------------------------------------------------------------------------------------*/
-- 应付与付款对账
SELECT  Q.*,  R.F_NAME AS F_DEALINGSNAME, P.F_CONTRACTNO, Q.F_WORKNO, P.F_REMARK,
              Q.F_APAMT-Q.F_PAMT AS F_AMT  
FROM
(
SELECT B.F_ARPID AS F_BILLID, B.F_DEALINGSID, LEFT(B.F_DATE, 10) AS F_DATE, A.F_PURBILLID,  
           SUM(IFNULL(A.F_AMT, 0)) AS F_APAMT, 0 AS F_PAMT, B.F_WORKNO, B.F_REMARK   
FROM ACC_ARPBILLBODY A
LEFT JOIN ACC_ARPBILLHEAD B ON(A.F_ARPID=B.F_ARPID)
WHERE B.F_DEALINGSID=:F_SUPPLIERID AND B.F_STATUS>='5'
GROUP BY  B.F_ARPID, B.F_DEALINGSID, B.F_DATE, A.F_PURBILLID,B.F_WORKNO, B.F_REMARK

UNION ALL

SELECT B.F_RPID AS F_BILLID, B.F_DEALINGSID, LEFT(B.F_DATE, 10) AS F_DATE, A.F_PURBILLID, 
       0 AS F_APAMT, SUM(IFNULL(F_ACTAMT, 0)) AS F_PAMT, B.F_WORKNO, B.F_REMARK   
FROM ACC_RPBILLBODY A
LEFT JOIN ACC_RPBILLHEAD B ON(A.F_RPID=B.F_RPID)
WHERE B.F_DEALINGSID=:F_SUPPLIERID AND B.F_STATUS>='5'
GROUP BY B.F_RPID, B.F_DEALINGSID, B.F_DATE, A.F_PURBILLID,B.F_WORKNO, B.F_REMARK  

) Q 
LEFT JOIN DB_ORGS R ON(Q.F_DEALINGSID=R.F_ID)
LEFT JOIN PUR_ORDERHEAD P ON(Q.F_PURBILLID=P.F_BILLID)
ORDER BY F_PURBILLID, F_DATE, F_BILLID

---------------------------------------------------------------------------------------------------
-- 数据验证
SELECT A.F_APPROVETIME,A.F_BILLID,A.F_SUPPLIER,A.F_CURRENCY AS 采购订单币别,
B.F_CURRENCY AS 供应商档案币别,
A.F_AMT,A.F_APAMT,A.F_PAMT,IFNULL(A.F_APAMT,0)-IFNULL(A.F_PAMT,0) AS 应付减已付

FROM PUR_ORDERHEAD A
LEFT JOIN DB_ORGS B ON A.F_SUPPLIERID=B.F_ID
WHERE A.F_CURRENCY<>B.F_CURRENCY
ORDER BY A.F_APPROVETIME DESC,IFNULL(A.F_APAMT,0)-IFNULL(A.F_PAMT,0)

---------------------------------------------------------------------------------------------------

SELECT S.F_SUPPLIERID, Q.F_WHSID, Q.PUR_BILLID, Q.F_GOODSID, Q.ITEMID, 
            SUM(Q.F_QTY) AS QTY, SUM(Q.CH_QTY) AS CH_QTY, R.F_ID
FROM 
(

SELECT A.F_WHSID, A.F_BILLID AS PUR_BILLID, A.F_BILLITEMID AS ITEMID, B.F_CONTRACTNO, A.F_GOODSID, IFNULL(A.F_QTY, 0) AS F_QTY, 0 AS CH_QTY
FROM INV_GOODSLIVE A
LEFT JOIN PUR_ORDERHEAD B ON(A.F_BILLID=B.F_BILLID)

/**采购订单****/
UNION ALL
SELECT B.F_SUPPLIERID AS F_WHSID, B.F_BILLID AS PUR_BILLID, A.F_ID AS ITEMID, B.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, 
          IFNULL(IF(A.F_MODIFYQTY, F_LASTQTY, A.F_QTY), 0) AS CH_QTY  
FROM PUR_ORDERBODY A
LEFT JOIN PUR_ORDERHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS='5' AND B.F_MODEL='0'

UNION ALL
SELECT B.F_SUPPLIERID AS F_WHSID, B.F_BILLID AS PUR_BILLID, A.F_ID AS ITEMID, B.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, 
     IFNULL(A.F_RECVQTY, 0) AS CH_QTY  
FROM PUR_ORDERBODY A
LEFT JOIN PUR_ORDERHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS='8' AND B.F_MODEL='0'

/***仓库单据*****/
/**0.采购入库单****/
UNION ALL
SELECT IFNULL(A.F_FROMORGID, B.F_FROMORGID) AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, 
             A.F_GOODSID, 0 AS F_QTY, -1 * IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='0'

UNION ALL
SELECT IFNULL(A.F_TOORGID, B.F_TOORGID) AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='0'

/**1.采购退货单****/
UNION ALL
SELECT B.F_FROMORGID AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, -1 * IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='1'

UNION ALL
SELECT IFNULL(A.F_TOORGID, B.F_TOORGID) AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='1'

/*A. 送货单****/
UNION ALL
SELECT IFNULL(A.F_FROMORGID, B.F_FROMORGID) AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, -1 * IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='A'

UNION ALL
SELECT IFNULL(A.F_TOORGID, B.F_TOORGID) AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='A'

/*2.调拨单******/
UNION ALL
SELECT IFNULL(A.F_FROMORGID, B.F_FROMORGID) AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, -1 * IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='2'

UNION ALL
SELECT IFNULL(A.F_TOORGID, B.F_TOORGID) AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='2'

/*3.销售出库单" */
UNION ALL
SELECT B.F_FROMORGID AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, -1 * IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='3'

/*4.销售退货单" */
UNION ALL
SELECT B.F_TOORGID AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='4'

/*X.采购入库(调拨单)*/
UNION ALL
SELECT IFNULL(A.F_FROMORGID, B.F_FROMORGID) AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, -1 * IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='X'

UNION ALL
SELECT IFNULL(A.F_TOORGID, B.F_TOORGID) AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='X'


/***  ["I", "其它入库单(盘盈)"] ***/
UNION ALL
SELECT B.F_TOORGID AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='I'

UNION ALL
SELECT B.F_FROMORGID AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, -1*IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='I'

/***  ["O", "其它出库单(盘亏)"] ***/
UNION ALL
SELECT B.F_FROMORGID AS F_WHSID, A.F_SOURCEBILLID AS PUR_BILLID, A.F_SOURCEITEMID AS ITEMID, A.F_CONTRACTNO, A.F_GOODSID, 0 AS F_QTY, -1 * IFNULL(A.F_ACTQTY, 0) AS CH_QTY  
FROM INV_CHANGEBODY A
LEFT JOIN INV_CHANGEHEAD B ON(A.F_BILLID=B.F_BILLID)
WHERE B.F_STATUS>='5' AND B.F_BILLTYPE='O'

) Q 
LEFT JOIN PUR_ORDERBODY R ON(R.F_ID=Q.ITEMID)
LEFT JOIN PUR_ORDERHEAD S ON(R.F_BILLID=S.F_BILLID)
GROUP BY S.F_SUPPLIERID, Q.F_WHSID, Q.PUR_BILLID, Q.F_GOODSID, Q.ITEMID
HAVING QTY<>CH_QTY
ORDER BY F_WHSID, PUR_BILLID, F_GOODSID, ITEMID

---------------------------------------------------------------------------------------------------

--预制发票
-- 条件
SELECT A.F_INVID, A.F_INVDATE, A.F_SELLERNAME, A.F_PURCHASERNAME 
FROM ACC_INVHEAD A 
WHERE A.F_INVID = :INVID 
--
-- 采购发票表
SELECT  CONCAT(" ", A.F_INVID, "\'") AS 发票号码, DATE_FORMAT(A.F_INVDATE, '%%Y-%%m-%%d') AS 发票日期, 
        CONCAT("公司名称：", A.F_PURCHASERNAME) AS 购方名称, 
        CONCAT("纳税人识别号：", A.F_PURCHASERREGCODE) AS 购方纳税人识别号, 
        CONCAT("开票地址：", substring_index(A.F_PURCHASERADDRESS, "0", 1)) AS 购方地址,
        CONCAT("电话：", RIGHT(A.F_PURCHASERADDRESS, 13)) AS 电话, 
        CONCAT("开户银行：", substring_index(A.F_PURCHASERBANKINFO, "行", 2), "行") AS 购方开户行,
        CONCAT("银行账号：", substring_index(A.F_PURCHASERBANKINFO, "行", -1)) AS 银行账号, 
        A.F_SELLERNAME AS 售方名称, 
        A.F_SELLERREGCODE AS 售方纳税人识别号, 
        A.F_SELLERADDRESS AS 售方地址, 
        A.F_SELLERBANKINFO AS 售方开户行, 
        B.F_ITEMNAME AS 名称,B.F_ITEMTYPE AS 规格型号, B.F_UNIT AS 单位, B.F_QTY AS 数量, B.F_PRICE AS 单价, 
        CONVERT(B.F_NETAMT+B.F_TAX, decimal(10,2)) AS 金额, B.F_TAXRATE AS 税率, 
        CONVERT(B.F_TAX, decimal(10,2)) AS 税额, A.F_REMARK AS 备注, A.F_WORKNO AS 工作号, 
        DATE_FORMAT(C.F_ACTSHIPDATE, "%%Y-%%m-%%d") AS 装柜日期, A.F_WORKNO 工作号 
FROM ACC_INVHEAD A  
LEFT JOIN ACC_INVBODY B ON A.F_INVID = B.F_INVID 
LEFT JOIN MPS_SOWORKNO C ON A.F_WORKNO = C.F_WORKNO 
WHERE A.F_INVID=:ID 
WHERE A.F_INVID=66201911050022 


--66201910260002
-- WHERE A.F_INVID = 66201910260025


SELECT B.F_ITEMTYPE AS 规格型号, B.F_UNIT AS 单位, B.F_QTY AS 数量, B.F_PRICE AS 单价, 
        B.F_NETAMT AS 金额, B.F_TAXRATE AS 税率, B.F_TAX AS 税额 
FROM ACC_INVBODY B 

---
-- 主表
SELECT A.F_INVID AS 发票号码, DATE_FORMAT(A.F_INVDATE, '%%Y-%%m-%%d') AS 发票日期, 
        A.F_PURCHASERNAME AS 购方名称, A.F_PURCHASERADDRESS AS 购方地址, 
        A.F_PURCHASERREGCODE AS 购方纳税人识别号, A.F_PURCHASERBANKINFO AS 购方开户行, 
        A.F_SELLERNAME AS 销售方名称, A.F_SELLERREGCODE AS 售方纳税人识别号, A.F_SELLERADDRESS AS 销售方地址, 
        A.F_SELLERBANKINFO AS 销售方开户行, B.F_ITEMNAME AS 名称, B.F_ITEMTYPE AS 规格型号, B.F_UNIT AS 单位, 
        B.F_QTY AS 数量, B.F_PRICE AS 单价, ROUND(B.F_NETAMT,2) AS 金额, B.F_TAXRATE AS 税率, 
        ROUND(B.F_TAX, 2) AS 税额, B.F_REMARK AS 备注 
FROM ACC_INVHEAD A 
LEFT JOIN ACC_INVBODY B ON A.F_INVID = B.F_INVID 
WHERE A.F_INVID = :ID 

---------------------------------------------------------------------------------------------------

SELECT B.F_BILLID,B.F_APPROVETIME,B.F_SERVICETYPE,B.F_WORKNO,A.F_BOXIDX,A.F_BOXNO,A.F_BOXSN,
        D.F_BOXMODEL,A.F_GOODSID,C.F_GOODSCODE,
        IF(instr(C.F_GOODSCODE,'-')>0,substr(C.F_GOODSCODE,1,instr(C.F_GOODSCODE,'-')-1),C.F_GOODSCODE) AS 原金蝶物料代码,
        C.F_GOODSNAME,C.F_GOODSENAME,C.F_GOODSMODEL,C.F_GOODSPACKAGEMODEL,
        C.F_MPSUNIT,A.F_ACTQTY/C.F_MPSUNITEXRATE AS F_ACTQTY,A.F_FEE AS 单位额外费用,
        A.F_COLORNO AS 色号,A.F_PACKAGEKIND AS 打托方式,A.F_GROSSWEIGHT/A.F_WEIGHTRATE AS 毛重,
        A.F_NETWEIGHT/A.F_WEIGHTRATE AS 净重,A.F_WEIGHTUNIT AS 重量单位,A.F_TOTALWEIGHT AS 总重量吨,
        A.F_TOTALCCWEIGHT AS 报关重量吨,A.F_PRICE*C.F_MPSUNITEXRATE AS 单价,A.F_AMT AS 金额,
        A.F_CCPRICE*C.F_MPSUNITEXRATE AS 报关价,A.F_TAXRETURN AS 退税率,A.F_TAXADDED AS 增值税率,
        (CASE WHEN B.F_SERVICETYPE IN ('01','02','03','04') THEN A.F_AMT*A.F_TAXRETURN/(1+A.F_TAXADDED) ELSE 0 END )  AS 总退税额,
        IFNULL(A.F_FROMORGID,B.F_FROMORGID) AS F_FROMORGID,
        IFNULL(A.F_FROMORGNAME,B.F_FROMORGNAME) AS F_FROMORGNAME,IFNULL(A.F_TOORGID,B.F_TOORGID) AS F_TOORGID,
        IFNULL(A.F_TOORGNAME,B.F_TOORGNAME) AS 目标组织名称,A.F_SOURCEBILLID AS 采购单号,A.F_CONTRACTNO AS 合同号,
        A.F_SUPPLIERID,A.F_SUPPLIER AS 供应商,F.F_REMARK AS 备注,I.F_HSGOODSCNAME AS 开票名称,G.F_CURRENCY AS 币别,
        G.F_EXRATE AS 汇率,A.F_AMT*G.F_EXRATE AS 金额RMB,J.F_INVOICENO

FROM INV_CHANGEBODY A
JOIN INV_CHANGEHEAD B ON A.F_BILLID=B.F_BILLID
JOIN BAS_GOODS C ON A.F_GOODSID=C.F_GOODSID
LEFT JOIN MPS_SOBOXNO D ON (B.F_WORKNO=D.F_WORKNO AND A.F_BOXIDX=D.F_BOXIDX AND A.F_BOXNO=D.F_BOXNO)
LEFT JOIN MPS_PREBODY E ON A.F_PREITEMID=E.F_ID
LEFT JOIN MPS_SOBODY F ON  F.F_ID=E.F_SOURCEITEMID
LEFT JOIN PUR_ORDERHEAD G ON G.F_BILLID=A.F_SOURCEBILLID
LEFT JOIN BAS_HSGOODS I ON C.F_CCGOODSID=I.F_HSGOODSID
LEFT JOIN MPS_SOWORKNO J ON J.F_WORKNO=B.F_WORKNO
WHERE B.F_BILLTYPE='3' AND B.F_STATUS>=5
AND B.F_APPROVETIME>=:START_DATE AND B.F_APPROVETIME<=DATE_ADD(:END_DATE,interval 1 day)
AND (:工作号='' OR B.F_WORKNO LIKE CONCAT('%',:工作号,'%'))
AND ( :目标组织名称='' OR IFNULL(A.F_TOORGNAME,B.F_TOORGNAME) LIKE CONCAT('%', :目标组织名称,'%'))

--明细账
SELECT A.F_CADATE, A.F_CASN, A.F_SUBJECT, B.F_DRAMT AS 借方金额, B.F_CRAMT AS 贷方金额, 
        B.F_ACCOUNTNAME, C.F_BALANCETYPE AS 余额方向, 
        IF(C.F_BALANCETYPE="借方", (B.F_DRAMT-B.F_CRAMT), (B.F_CRAMT-B.F_DRAMT)) AS 余额 
FROM ACC_CAHEAD A 
JOIN ACC_CABODY B ON A.F_BILLID = B.F_BILLID 
LEFT JOIN BAS_SUBJECTS C ON B.F_ID = C.F_SUBJECTID 
WHERE A.F_CADATE >= :START_DATE AND A.F_CADATE <= DATE_ADD(:END_DATE, INTERVAL 1 DAY) 


WHERE A.F_CADATE >= "2018-11-19" AND A.F_CADATE <= DATE_ADD("2018-11-20", INTERVAL 1 DAY)

------------------------------------


